# 参见 https://github.com/lycheeverse/lychee#configuration-file
exclude = [
  "http://localhost",
  "https://localhost",
  "http://127.0.0.1",
  "https://127.0.0.1"
]
retry_wait_time = 2
max_retries = 2
timeout = 20
user_agent = "Plurality Wiki CI"
