site_name: Multiple Personality System Wiki - 多意识体百科
site_url: https://mpswiki.pages.dev
site_description: 多重意识体系统（Plurality）与创伤相关主题的中文知识库
site_author: 脸脸系统、弦羽系统、逝水流年系统及社区贡献者
repo_url: https://github.com/mps-team-cn/Multiple_personality_system_wiki
repo_name: Multiple_personality_system_wiki
copyright: Copyright &copy; 2024-2025 Multiple Personality System Wiki
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  # custom_dir: overrides  # 暂时注释,需要时可创建该目录进行主题自定义

  # 颜色配置
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

  # 字体配置
  font:
    text: Noto Sans SC
    code: JetBrains Mono

  # 图标
  icon:
    repo: fontawesome/brands/github
    logo: material/book-open-variant

  # 功能特性
  features:
    # 导航
    - navigation.instant # 即时加载
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 显示加载进度
    - navigation.tracking # 地址栏跟踪
    - navigation.tabs # 顶部标签页
    - navigation.tabs.sticky # 固定标签页
    - navigation.sections # 导航分组
    - navigation.expand # 默认展开导航
    - navigation.path # 面包屑导航
    - navigation.indexes # 分组索引页
    - navigation.top # 返回顶部按钮
    - navigation.footer # 页脚导航

    # 目录
    - toc.follow # 目录跟随
    # - toc.integrate             # 不启用，改用 CSS 控制布局

    # 搜索
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享

    # 代码
    - content.code.copy # 代码复制按钮
    - content.code.select # 代码选择
    - content.code.annotate # 代码注释

    # 内容
    - content.tabs.link # 内容标签链接
    - content.tooltips # 工具提示
    - content.footnote.tooltips # 脚注工具提示

    # 其他
    - announce.dismiss # 公告可关闭
    - content.action.edit # ← 开启“编辑此页”图标
    - content.action.view # （可选）旁边再加“查看源码”

# 额外配置
extra:
  # 社交链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mps-team-cn/plurality_wiki
      name: GitHub 仓库

  # 分析（本地开发时注释，部署时启用）
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: 这个页面有帮助吗?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 很有帮助
          data: 1
          note: >-
            感谢您的反馈!
        - icon: material/emoticon-sad-outline
          name: 有待改进
          data: 0
          note: >-
            感谢您的反馈! 请在
            <a href="https://github.com/mps-team-cn/plurality_wiki/issues" target="_blank" rel="noopener">GitHub</a>
            提出改进建议。

  # 版本控制（暂未启用，计划中）
  # version:
  #   provider: mike

  # 替代语言（暂未启用多语言支持）
  # alternate:
  #   - name: 简体中文
  #     link: /
  #     lang: zh
  #   - name: English
  #     link: /en/
  #     lang: en

# 额外样式和脚本
extra_css:
  - assets/extra-material.css # Material 主题专用增强样式

extra_javascript:
  - assets/extra.js

# Markdown 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: 链接到本节
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower-ascii

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: mps-team-cn
      repo: Multiple_personality_system_wiki
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower-ascii
  - pymdownx.tasklist:
      custom_checkbox: true

# 插件
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - zh
        - en

  - tags

  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: timeago
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

# 导航结构
nav:
  - 首页: index.md
  - 快速开始:
      - 快速入门: QuickStart.md
      - 贡献指南: CONTRIBUTING.md
      - 更新日志: changelog.md
      - 序言: Preface.md
  - 词条索引:
      - 标签索引: tags.md
      - 术语表: Glossary.md
  - 核心概念:
      - 核心概念导览: entries/Core-Concepts-Guide.md
      - 基础概念:
          - entries/Dissociation.md
          - entries/Plurality.md
          - entries/System.md
          - entries/Alter.md
      - 临床诊断:
          - entries/DID.md
          - entries/OSDD.md
          - entries/Partial-Dissociative-Identity-Disorder-PDID.md
      - 健康多意识体:
          - entries/Tulpa.md
          - entries/Emmengard-Classification.md
          - entries/Soulbond.md
      - 理论框架:
          - entries/Structural-Dissociation-Theory.md
          - entries/Apparently-Normal-Part-Emotional-Part-Model.md
          - entries/Personality-Structure-Theory.md
  - 系统运作:
      - 系统运作导览: entries/System-Operations.md
      - 前台与切换:
          - entries/Front-Fronting.md
          - entries/Switch.md
          - entries/Co-Fronting.md
      - 意识共享与记忆:
          - entries/Co-Consciousness.md
          - entries/Memory-Holder.md
          - entries/Memory-Shielding.md
      - 内部空间与沟通:
          - entries/Headspace-Inner-World.md
          - entries/Internal-Communication.md
          - entries/Permissions.md
      - 角色与治理:
          - entries/System-Roles.md
          - entries/Admin.md
          - entries/Host.md
          - entries/Gatekeeper.md
          - entries/Protector.md
          - entries/Internal-Self-Helper-ISH.md
  - 心理健康:
      - 心理健康导览: entries/Mental-Health-Guide.md
      - entries/Dissociation.md
      - entries/PTSD.md
      - entries/CPTSD.md
      - entries/Trauma.md
      - entries/Grounding.md
  - 实践指南:
      - 实践指南导览: entries/Practice-Guide.md
      - Tulpa 创造指南:
          - 指南总览: entries/Tulpa-Guide.md
          - 基础篇: entries/Tulpa-Guide-1.md
          - 实践篇: entries/Tulpa-Guide-2.md
          - 提高篇: entries/Tulpa-Guide-3.md
      - 意识训练:
          - entries/Meditation.md
          - entries/Visualization-Imagination.md
          - entries/Attention-Awareness.md
      - 内部协作:
          - entries/Internal-Communication.md
          - entries/Headspace-Inner-World.md
          - entries/Permissions.md
      - 稳定技巧:
          - entries/Grounding.md
          - entries/Sensory-Regulation-Strategies.md
          - entries/Emotion-Regulation.md

# 严格模式
strict: false

# 开发服务器
dev_addr: 127.0.0.1:8000

# 文档目录
docs_dir: docs

# 站点目录
site_dir: site

# 不需要 MkDocs 处理的文件（保持原样复制）
not_in_nav: |
  /admin/
