# 本地开发模式：使用 test-repo（无需 GitHub 认证）
# 部署到生产环境时，需要切换回 github backend

backend:
  name: test-repo

media_folder: "docs/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "entries"
    label: "词条"
    label_singular: "词条"
    folder: "docs/entries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "英文名", name: "en", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", default: [] }
      - { label: "更新时间", name: "updated", widget: "datetime", format: "YYYY-MM-DD", default: "" }
      - { label: "正文", name: "body", widget: "markdown" }
