name: 文档质量检查

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdownlint:
    name: Markdown 语法校验
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 配置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: 安装 markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: 执行 markdownlint
        run: markdownlint "**/*.md" --ignore "node_modules" --ignore "tools/pdf_export/vendor"

  linkcheck:
    name: 链接有效性检查（本地解析）
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 运行 lychee（本地解析根路径）
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config .github/lychee.toml
            --root-dir "${{ github.workspace }}"
            --no-progress
            --verbose
            ./

  linkcheck-pages:
    name: 线上巡检（GitHub Pages）
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lychee remap 到 GitHub Pages
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config .github/lychee.toml
            --remap '^/entries/ https://kuliantnt.github.io/plurality_wiki/#/entries/'
            --no-progress
            --verbose
            ./

  linkcheck-cf:
    name: 线上巡检（Cloudflare）
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lychee remap 到 Cloudflare
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config .github/lychee.toml
            --remap '^/entries/ https://plurality-wiki.pages.dev/#/entries/'
            --no-progress
            --verbose
            ./
